"""G32 — Verify that the assistant text generated by the LLM is recorded in the session log."""

from __future__ import annotations

import json
import os
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from hermit_agent.session_logger import SessionLogger


def _make_session_dir(tmp: str) -> str:
    session_dir = os.path.join(tmp, ".hermit", "session")
    os.makedirs(session_dir, exist_ok=True)
    return session_dir


def test_log_assistant_text_writes_to_jsonl_only():
    """session.log removal — assistant text remains only in the JSONL."""
    with tempfile.TemporaryDirectory() as tmp:
        logger = SessionLogger(session_dir=_make_session_dir(tmp))
        logger.log_assistant_text("Task complete. Suggested next step: ...")
        # Text log file is not created
        session_log = os.path.join(tmp, ".hermit", "session.log")
        assert not os.path.exists(session_log)
        # Recorded in JSONL
        with open(logger.jsonl_path, encoding="utf-8") as f:
            body = f.read()
        assert "Task complete" in body


def test_log_assistant_text_writes_to_jsonl():
    with tempfile.TemporaryDirectory() as tmp:
        logger = SessionLogger(session_dir=_make_session_dir(tmp))
        logger.log_assistant_text("Summary message")
        records = []
        with open(logger.jsonl_path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    records.append(json.loads(line))
        ar = [r for r in records if r.get("type") == "assistant"]
        assert len(ar) == 1
        assert ar[0]["content"][0]["text"] == "Summary message"


def test_system_prompt_requires_trailing_summary():
    """`_STATIC_SYSTEM_PROMPT` must include a phrase requesting a text summary at the end of the turn."""
    from hermit_agent.loop import _STATIC_SYSTEM_PROMPT

    # Must include one of the directives related to "prohibit silent turn termination" + "summary"
    assert "summary" in _STATIC_SYSTEM_PROMPT.lower()
    # Key keywords: prohibit ending silently/silent termination
    assert (
        "silent" in _STATIC_SYSTEM_PROMPT.lower()
        or "silently" in _STATIC_SYSTEM_PROMPT
        or "never end silently" in _STATIC_SYSTEM_PROMPT.lower()
    )
